# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '8.0'
use_frameworks!

target 'transients' do
	#pod 'Alamofire', '~> 1.2.3'
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
	pod 'SwiftyJSON', '~> 2.2.0'
end

target 'transientsTests' do

end

