# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '8.0'
use_frameworks!

target 'transients' do
	#pod 'Alamofire', '~> 1.2.3'
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
	pod 'SwiftyJSON', '~> 2.2.0'
	pod 'MotionKit'
end

def testing_pods
	# If you're using Xcode 7 / Swift 2
	#pod 'Quick', '~> 0.6.0'
	#pod 'Nimble', '2.0.0-rc.2'
	
	# If you're using Xcode 6 / Swift 1.2
	pod 'Quick', '~> 0.3.0'
	pod 'Nimble', '~> 1.0.0'
end

target 'transientsTests' do
	testing_pods
end

